[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from = "/convert-image" # For image-to-image
  to = "/.netlify/functions/convert-image" # Use the corrected version from last step
  status = 200

[[redirects]] # New redirect for image-to-pdf
  from = "/image-to-pdf"
  to = "/.netlify/functions/image-to-pdf"
  status = 200