[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]] # New redirect for image conversion
  from = "/convert-image"
  to = "/.netlify/functions/convert-image"
  status = 200